workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
    scripts:
      - name: Clean
        script: |
          flutter clean
      - name: Get dependencies
        script: |
          flutter pub get
      - name: CocoaPods (iOS deps)
        script: |
          cd ios
          pod install --repo-update || true
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        # Option A: Recommended -> Use App Store Connect API key (preferred)
        api_key:
          key_id: ZA3FMVBTUQ
          issuer_id: 085de4f1-be1c-49a9-ac30-244e70f6fb52
          private_key: $APP_STORE_PRIVATE_KEY
        app_id: 6752672198
        submit_for_review: false
        notify_testers: false
